enabled: true
status: enabled
title: Fjord
description: A minimal blogging theme
supportedData: [medium]
weight: 1
author: Stackbit
authorURL: https://www.stackbit.com
images:
  small: images/demo-256x192.png
  large: images/demo-1024x768.png
